// Données effectif avec informations de salaire
window.staffData = [
    // DIRECTION
    { 
        id: 1, 
        nom: "Karl Pierce", 
        grade: "Directeur",
        matricule: "01",
        idUnique: "196219",
        departement: "Direction", 
        email: "karl.pierce@ems.fw",
        role: "Direction",
        hourlyRate: 7000,
        hoursPerWeek: 20,
        salaryGrid: "supervision"
    },
    { 
        id: 2, 
        nom: "Zak Carter", 
        grade: "Directeur Adjoint",
        matricule: "03",
        idUnique: "34940",
        departement: "Direction", 
        email: "zak.carter@ems.fw",
        role: "Direction",
        hourlyRate: 7000,
        hoursPerWeek: 20,
        salaryGrid: "supervision"
    },

    // COMMANDER
    { 
        id: 3, 
        nom: "Kahverengi Yildiz", 
        grade: "Commander",
        matricule: "07",
        idUnique: "65711",
        departement: "Supervision", 
        email: "kahverengi.yildiz@ems.fw",
        role: "Supervision",
        hourlyRate: 5500,
        hoursPerWeek: 20,
        salaryGrid: "supervision"
    },
    { 
        id: 4, 
        nom: "Mike Mouk", 
        grade: "Commander",
        matricule: "05",
        idUnique: "77323",
        departement: "Supervision", 
        email: "mike.mouk@ems.fw",
        role: "Supervision",
        hourlyRate: 5500,
        hoursPerWeek: 20,
        salaryGrid: "supervision"
    },

    // SENIOR PARAMEDIC
    { 
        id: 5, 
        nom: "Kader Yamaha", 
        grade: "Senior Paramedic",
        matricule: "09",
        idUnique: "49590",
        departement: "Supervision", 
        email: "kader.yamaha@ems.fw",
        role: "Supervision",
        hourlyRate: 5000,
        hoursPerWeek: 20,
        salaryGrid: "supervision"
    },

    // JUNIOR PARAMEDIC
    { 
        id: 6, 
        nom: "Tyron Fasol", 
        grade: "Junior Paramedic",
        matricule: "08",
        idUnique: "152149",
        departement: "Supervision", 
        email: "tyron.fasol@ems.fw",
        role: "Supervision",
        hourlyRate: 4000,
        hoursPerWeek: 20,
        salaryGrid: "supervision"
    },
    { 
        id: 7, 
        nom: "Niya Wahid", 
        grade: "Junior Paramedic",
        matricule: "94",
        idUnique: "238769",
        departement: "Supervision", 
        email: "niya.wahid@ems.fw",
        role: "Supervision",
        hourlyRate: 4000,
        hoursPerWeek: 20,
        salaryGrid: "supervision"
    },

    // MASTER EMT
    { 
        id: 8, 
        nom: "Mariposa Dos-sontos", 
        grade: "Master EMT",
        matricule: "80",
        idUnique: "89244",
        departement: "Supervision", 
        email: "mariposa.dossontos@ems.fw",
        role: "EMS",
        hourlyRate: 3750,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },

    // EMT ADVANCED
    { 
        id: 9, 
        nom: "Walker Johnson", 
        grade: "EMT Advanced",
        matricule: "77",
        idUnique: "152149",
        departement: "Supervision", 
        email: "walker.johnson@ems.fw",
        role: "EMS",
        hourlyRate: 3500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 10, 
        nom: "Osman Sahin", 
        grade: "EMT Advanced",
        matricule: "31",
        idUnique: "250135",
        departement: "Supervision", 
        email: "osman.sahin@ems.fw",
        role: "EMS",
        hourlyRate: 3500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 11, 
        nom: "Dustin Jones", 
        grade: "EMT Advanced",
        matricule: "44",
        idUnique: "200450",
        departement: "Supervision", 
        email: "dustin.jones@ems.fw",
        role: "EMS",
        hourlyRate: 3500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },

    // EMT INTERMEDIAIRE
    { 
        id: 12, 
        nom: "Dash Wild", 
        grade: "EMT Intermédiaire",
        matricule: "17",
        idUnique: "165552",
        departement: "Supervision", 
        email: "dash.wild@ems.fw",
        role: "EMS",
        hourlyRate: 3000,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 13, 
        nom: "Nina Périphérique", 
        grade: "EMT Intermédiaire",
        matricule: "90",
        idUnique: "70714",
        departement: "Supervision", 
        email: "nina.peripherique@ems.fw",
        role: "EMS",
        hourlyRate: 3000,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 14, 
        nom: "Yanis Bamba", 
        grade: "EMT Intermédiaire",
        matricule: "83",
        idUnique: "8720",
        departement: "Supervision", 
        email: "yanis.bamba@ems.fw",
        role: "EMS",
        hourlyRate: 3000,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 15, 
        nom: "Ali Chorba", 
        grade: "EMT Intermédiaire",
        matricule: "92",
        idUnique: "126256",
        departement: "Supervision", 
        email: "ali.chorba@ems.fw",
        role: "EMS",
        hourlyRate: 3000,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 16, 
        nom: "Kaïs Marshall", 
        grade: "EMT Intermédiaire",
        matricule: "54",
        idUnique: "250258",
        departement: "Supervision", 
        email: "kais.marshall@ems.fw",
        role: "EMS",
        hourlyRate: 3000,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },

    // EMT BASIC
    { 
        id: 17, 
        nom: "Maxime Rak", 
        grade: "EMT Basic",
        matricule: "24",
        idUnique: "232081",
        departement: "Supervision", 
        email: "maxime.rak@ems.fw",
        role: "EMS",
        hourlyRate: 2750,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 18, 
        nom: "Xenia Eliah", 
        grade: "EMT Basic",
        matricule: "19",
        idUnique: "151749",
        departement: "Supervision", 
        email: "xenia.eliah@ems.fw",
        role: "EMS",
        hourlyRate: 2750,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 19, 
        nom: "Yassine Zerouni", 
        grade: "EMT Basic",
        matricule: "78",
        idUnique: "148160",
        departement: "Supervision", 
        email: "yassine.zerouni@ems.fw",
        role: "EMS",
        hourlyRate: 2750,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 20, 
        nom: "Miguel Diaz", 
        grade: "EMT Basic",
        matricule: "67",
        idUnique: "251741",
        departement: "Supervision", 
        email: "miguel.diaz@ems.fw",
        role: "EMS",
        hourlyRate: 2750,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 21, 
        nom: "Nessayem Bensalah", 
        grade: "EMT Basic",
        matricule: "15",
        idUnique: "100975",
        departement: "Supervision", 
        email: "nessayem.bensalah@ems.fw",
        role: "EMS",
        hourlyRate: 2750,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },

    // EMR
    { 
        id: 22, 
        nom: "Brams Sko", 
        grade: "EMR",
        matricule: "91",
        idUnique: "143639",
        departement: "Supervision", 
        email: "brams.sko@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 23, 
        nom: "Friandises Saydou", 
        grade: "EMR",
        matricule: "69",
        idUnique: "233309",
        departement: "Supervision", 
        email: "friandises.saydou@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 24, 
        nom: "James Wood", 
        grade: "EMR",
        matricule: "93",
        idUnique: "206520",
        departement: "Supervision", 
        email: "james.wood@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 25, 
        nom: "Sofyane Anderson", 
        grade: "EMR",
        matricule: "14",
        idUnique: "253326",
        departement: "Supervision", 
        email: "sofyane.anderson@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 26, 
        nom: "Guzman Ruiz", 
        grade: "EMR",
        matricule: "13",
        idUnique: "50937",
        departement: "Supervision", 
        email: "guzman.ruiz@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 27, 
        nom: "Horacio Montero", 
        grade: "EMR",
        matricule: "24",
        idUnique: "85526",
        departement: "Supervision", 
        email: "horacio.montero@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 28, 
        nom: "Bakhaw Brooks", 
        grade: "EMR",
        matricule: "42",
        idUnique: "142751",
        departement: "Supervision", 
        email: "bakhaw.brooks@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 29, 
        nom: "Daniels Brooks", 
        grade: "EMR",
        matricule: "37",
        idUnique: "251916",
        departement: "Supervision", 
        email: "daniels.brooks@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 30, 
        nom: "Jessie Perez", 
        grade: "EMR",
        matricule: "20",
        idUnique: "144556",
        departement: "Supervision", 
        email: "jessie.perez@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 31, 
        nom: "Ayden Baraoui", 
        grade: "EMR",
        matricule: "63",
        idUnique: "102106",
        departement: "Supervision", 
        email: "ayden.baraoui@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 32, 
        nom: "Derya Gaviria", 
        grade: "EMR",
        matricule: "34",
        idUnique: "90799",
        departement: "Supervision", 
        email: "derya.gaviria@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 33, 
        nom: "Marco Martinez", 
        grade: "EMR",
        matricule: "30",
        idUnique: "203272",
        departement: "Supervision", 
        email: "marco.martinez@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 34, 
        nom: "William News", 
        grade: "EMR",
        matricule: "63",
        idUnique: "252875",
        departement: "Supervision", 
        email: "william.news@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },
    { 
        id: 35, 
        nom: "Angelina Hilton", 
        grade: "EMR",
        matricule: "79",
        idUnique: "2127",
        departement: "Supervision", 
        email: "angelina.hilton@ems.fw",
        role: "EMS",
        hourlyRate: 2500,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    },

    // INFIRMAIRE
    { 
        id: 36, 
        nom: "Swan Lee", 
        grade: "Infirmaire",
        matricule: "22",
        idUnique: "149625",
        departement: "Supervision", 
        email: "swan.lee@ems.fw",
        role: "EMS",
        hourlyRate: 2000,
        hoursPerWeek: 20,
        salaryGrid: "ems"
    }
];;
